### ISSUE TITLE
MCE::Map usage breaks CGI(::Application)

### ISSUE THREAD

**Issue by TheRealCuran** [marioroy/mce-perl#1]
I've a web application using CGI::Application at its web-facing core. This calls into various modules to construct the output. If I use MCE::Map (1.803) in my list generating modules and invoke a subroutine which uses mce_map, I get an "End of script output before headers" internal server error in Apache.

The CGI::Application is structured like this: FCGI script calls into MyWebApp::Dispatcher which calls into the respective module of the web application.
The FCGI script is:

``` perl
use strict;
use warnings;
use utf8;
binmode STDOUT, ':encoding(utf-8)';

use CGI::Fast;
use FCGI::ProcManager;
use MyWebApp::Dispatcher;

my $oProcMan = FCGI::ProcManager -> new({n_processes => 15});
$oProcMan->pm_manage();

my $oCgi;

while($oCgi = CGI::Fast->new()) {
        $oProcMan->pm_pre_dispatch();

        MyWebApp::Dispatcher->dispatch(
                args_to_new => {QUERY => $oCgi}
        );

        $oProcMan->pm_post_dispatch();
}
```

The dispatcher looks like:

``` perl
package MyWebApp::Dispatcher;

use strict;
use warnings;
use utf8;
binmode STDOUT, ":encoding(utf-8)";

use base 'CGI::Application::Dispatch';

sub dispatch_args {
    return {
        prefix  => 'MyWebApp',
        table   => [
            ''                  => { app => 'Main', rm => 'dashboard' },
            ':app/:rm?/:id?'    => {},
        ]
    };
}
```

An example application might look like:

``` perl
package MyWebApp::Example;

use strict;
use warnings;
use utf8;
binmode STDOUT, ':encoding(utf-8)';

use base 'MyWebApp';
use MyCore::Example::List;

sub setup {
    my $self = shift;

    $self->run_modes({
        'ajaxTest'          => \&ajaxTest,
    });
}

sub ajaxTest {
    my $self = shift;
    my $sQuery = $self->query->param('POSTDATA');

    # do lots of stuff and call into the mce_map containing method
    my $oList = MyCore::Example::List->new; # Moo-base object with MCE::Map
    my $hRet = $oList->genListFromQuery($sQuery);

    $self->header_add(-type => 'application/json; charset=UTF-8');
    # if I log the output of $hRet here I get what I expect
    return encode_json($hRet); # the return kills the FCGI
}
```

The base class `MyWebApp` is really boring and just sets up the configuration, session handling and DB connection.
Everything that returns before the call into `genListFromQuery()` works as expected. Moving the `header_add` call doesn't help, since that is all going to a buffer before the actual write by `CGI::Application` happens. This leaves me with the assumption, that MCE::Map is writing to STDOUT or STDERR somewhere.

Running the same code on the CLI works (even though MCE::Map seems to leave a ton of empty directories in /tmp).

**Comment by marioroy** [comment]
It seems that MCE::Map isn't happy somehow. I'm not able to see it, unfortunately. If possible, can you email me `MyCore::Example::List` so that I can see how MCE::Map is used. Typically, MCE removes its temporary directory when exiting.

Thanks.

**Comment by marioroy** [comment]
I have verified CGI::Fast, FCGI::ProcManager, and MCE. Currently, one cannot call `MCE::Map::init` when running with `FCGI`. Therefore, specify the default `max_workers` when loading `MCE::Map`.

``` perl
#!/usr/bin/perl

# usage http://127.0.0.1/cgi-bin/test_mce1.fcgi?size=8

use strict;
use warnings;

use MCE::Map max_workers => 3;

use CGI::Fast;
use FCGI::ProcManager;

my $count = 0;

my $proc_manager = FCGI::ProcManager->new({ n_processes => 4 });
$proc_manager->pm_manage();

while ( my $query = CGI::Fast->new() ) {
   $proc_manager->pm_pre_dispatch();

   print "Content-type: text/html\r\n\r\n";
   print "$$: ", ++$count, "<br>\n";
   print "<hr>\n";

   print "$_ = $ENV{$_}<br>\n" foreach sort keys %ENV;
   print "<hr>\n";

   my %params;

   foreach ( sort $query->param() ) {
      $params{$_} = $query->param($_);
      print $_, " = ", $params{$_}, "<br>\n";
   }

   print "<hr>\n";

   my @ret = mce_map { "$$: ".( $_ * 2 ) } 1 .. $params{'size'} || 8;

   print join("<br>\n", @ret), "<br>\n";

   $proc_manager->pm_post_dispatch();
}
```

The following is helpful during development on a development box/VM to reset the environment if necessary.

```
killall -TERM perl-fcgi perl-fcgi-pm ; service httpd restart
```

**Comment by marioroy** [comment]
It's possible to call `MCE::Map::init`. The following does the same thing.

``` perl
#!/usr/bin/perl

# usage http://127.0.0.1/cgi-bin/test_mce2.fcgi?size=8

use strict;
use warnings;

use MCE::Map;

use CGI::Fast;
use FCGI::ProcManager;

my ($first_time, $count) = (1, 0);

my $proc_manager = FCGI::ProcManager->new({ n_processes => 4 });
$proc_manager->pm_manage();

while ( my $query = CGI::Fast->new() ) {
   $proc_manager->pm_pre_dispatch();

   print "Content-type: text/html\r\n\r\n";
   print "$$: ", ++$count, "<br>\n";
   print "<hr>\n";

   print "$_ = $ENV{$_}<br>\n" foreach sort keys %ENV;
   print "<hr>\n";

   my %params;

   foreach ( sort $query->param() ) {
      $params{$_} = $query->param($_);
      print $_, " = ", $params{$_}, "<br>\n";
   }

   print "<hr>\n";

   if ( $first_time ) {
      MCE::Map::init( max_workers => 3 );
   }

   my @ret = mce_map { "$$: ".( $_ * 2 ) } 1 .. $params{'size'} || 8;

   print join("<br>\n", @ret), "<br>\n";

   $proc_manager->pm_post_dispatch();
}
```

**Comment by marioroy** [comment]
One may also include `MCE::Shared` if a shared counter between all processes involved is desired. When resetting, it is important to send the `TERM` signal so that the `MCE::Shared` manager process receives it.

```
killall -TERM perl-fcgi perl-fcgi-pm ; service httpd restart
```

The following is a demonstration utilizing `MCE::Shared` for the counter variable.

``` perl
#!/usr/bin/perl

# usage http://127.0.0.1/cgi-bin/test_mce3.fcgi?size=8

use strict;
use warnings;

use MCE::Map;
use MCE::Shared;

use CGI::Fast;
use FCGI::ProcManager;

# Shared variables must be defined before FCGI::ProcManager.
my $count = MCE::Shared->scalar( 0 );
my $first_time = 1;

my $proc_manager = FCGI::ProcManager->new({ n_processes => 4 });
$proc_manager->pm_manage();

# Optional, the following statement must come after $pm->pm_manage.
MCE::Shared->init(); # enables shared parallel-IPC capabilities

while ( my $query = CGI::Fast->new() ) {
   $proc_manager->pm_pre_dispatch();

   print "Content-type: text/html\r\n\r\n";
   print "$$: ", $count->incr(), "<br>\n";
   print "<hr>\n";

   print "$_ = $ENV{$_}<br>\n" foreach sort keys %ENV;
   print "<hr>\n";

   my %params;

   foreach ( sort $query->param() ) {
      $params{$_} = $query->param($_);
      print $_, " = ", $params{$_}, "<br>\n";
   }

   print "<hr>\n";

   if ( $first_time ) {
      MCE::Map->init( max_workers => 3 );
      $first_time = 0;
   }

   my @ret = mce_map { "$$: ".( $_ * 2 ) } 1 .. $params{'size'} || 8;

   print join("<br>\n", @ret), "<br>\n";

   $proc_manager->pm_post_dispatch();
}
```

**Comment by TheRealCuran** [comment]
Does this mean you no longer need `MyCore::Example::List`? Because it seems like you have found the issue and since I can't give you `MyCore::Example::List` directly I would need to produce a reduced test case for you.

The gist of what `MyCore::Example::List` (only the methods that call `mce_map`) does is however:

``` perl
package MyCore::Example::List;

use strict;
use warnings;
use utf8;
binmode STDOUT, ":encoding(utf-8)";

use Moo;
use MyCore::Utils::List;
use MCE::Map
    thaw    => \&MyCore::Utils::List::_thaw
;
use MyCore::Example;

with('MyCore');  # initialises (amongst other things) the DBIx::Class in $self->dbh

has hExamplesCache => (
    is  => 'rwp',
    default => sub { undef; }
);

has aExampleLst => (
    is  => 'rwp',
    default => sub { undef; }
);

sub populateExampleLst {
    my $self = shift;

    # some initial input validation and state setup

    my $oExampleRs = $self->dbh->resultset('TblExample')->search(
      {fld_some_constraint => {-is_not => undef}}, {order_by => 'fld_example_ts'});

    my @aExamples = $oExampleRs->all;
    my @aRes = mce_map {$_->fld_example_id} @aExamples;
    my %hCache = mce_map {$_->fld_example_id => $_} @aExamples;
    $self->_set_aExampleLst(\@aRes);
    $self->_set_hExamplesCache(\%hCache);
    return 1;
}

sub exampleGetObjectLst {
    my $self = shift;

    my @aTmp = mce_map {
        MyCore::Example->new({
            exampId     => $_,
            exampCache  => $self->hExamplesCache->{$_},
        });
    } @{$self->aExampleLst};

    return \@aTmp;
}

1;
```

Obviously I stripped out all error handling for better readability. But just to make this clear: we only hit the `mce_map` calls if there is actually something to do.

`MyCore::Utils::List::_thaw` only uses the `DBIx::Class` `thaw`, otherwise the resultsets are lost in `mce_map`.

The important `mce_map` call is the one in `exampleGetObjectLst`. The others are nice for speed, but not strictly required. Constructing a couple of the base objects just takes a bit of time. and doing that in parallel can cut down execution time significantly.

**Comment by marioroy** [comment]
I met to ask for a reduced use-case so that I can reproduce the issue. The following is lightly beneficial. Call `MCE::Map->finish()` immediately after running to shutdown the MCE workers. Likewise, inside `exampleGetObjectLst`.

``` perl
mce_map { ... } @data;
MCE::Map->finish();
```

**Comment by marioroy** [comment]
I'm not sure if the `Sereal` module is installed on your system. You may need to tell `MCE::Map` to not use it. I doubt that this is the reason. I'm out of ideas otherwise due to not able to reproduce.

``` perl
use MCE::Map Sereal => 0, thaw => \&MyCore::Utils::List::_thaw;
```

**Comment by TheRealCuran** [comment]
> I'm not sure if the Sereal module is installed on your system. You may need to tell MCE::Map to not use it. I doubt that this is the reason. I'm out of ideas otherwise due to not able to reproduce.

It was not, but disabling it had not the desired effect of making MCE::Map work with CGI::Application.

> The following may be beneficial for your use-case. Call MCE::Map->finish() immediately after running to shutdown the MCE workers. Likewise, inside exampleGetObjectLst.

This doesn't seem to change the request failure either. I'm still getting "End of script output before headers".

Give me a bit and I can send you the test case. ;-)

**Comment by TheRealCuran** [comment]
I've uploaded the [test case](https://github.com/marioroy/mce-perl/files/377761/mce-perl_issues_1.zip). Let me know if you need something else.

Please note, that I removed really everything not needed. This includes lots of input validation and error checking along the lines.

**Comment by marioroy** [comment]
Thank you for the concise test case.

In the README file, you mentioned having `perl.<PID>.<WID>` folders. On my CentOS 7 VM, I have one directory per each FCGI process. This is correct. No tempdir remains when running `test.cli.pl` from the command-line (not via Apache/FCGI). That is the expected behavior.

```
# Base temp directory for Apache/FCGI on CentOS 7.
/tmp/systemd-private-d0cb85e32faa4eddbf2abf13bfd43699-httpd.service-ndHepY/tmp/

# List of directories under the base temp directory.
perl-fcgi.6467.0
perl-fcgi.6468.0
perl-fcgi.6469.0
perl-fcgi.6470.0
perl-fcgi.6471.0
perl-fcgi.6472.0
perl-fcgi.6473.0
perl-fcgi.6474.0
perl-fcgi.6475.0
perl-fcgi.6476.0
perl-fcgi.6477.0
perl-fcgi.6478.0
perl-fcgi.6479.0
perl-fcgi.6480.0
perl-fcgi.6481.0
```

To get MCE working, the `posix_exit => 1` option is necessary when running with FCGI.

``` Perl
sub exampGetObjectLst {
        my $self = shift;

        MCE::Map->init( posix_exit => 1 );

        my @aTmp = mce_map {
                MyCore::Example->new({
                        exampId         => $_,
                        exampCache      => $self->hExampsCache->{$_}
                })
        } @{$self->aExampLst};

        MCE::Map->finish();

        return \@aTmp;
}
```

Your test case is working for me after adding the `posix_exit` option. That avoids all END and destructor processing for MCE workers. Basically, to not impact the FCGI process.

**Comment by TheRealCuran** [comment]
Thanks for your support! That was it. With `posix_exit => 1` I can use `MCE::Map` in my project! Thanks a lot!

Maybe that could be added to the documentation, that you need to set that option in an (F)CGI environment.

**Comment by marioroy** [comment]
The MCE `posix_exit` option is set to 1 automatically whenever `(F)CGI.pm` is present in the new MCE 1.804 release. The 3 FCGI examples were also added to `MCE::Examples`.

https://metacpan.org/release/MARIOROY/MCE-1.804

Thank you.
