### ISSUE TITLE
MCE::Loop and Visual Studio Code

### ISSUE THREAD

**Issue by thalia2809** [marioroy/mce-perl#15]
New here, so any advice appreciated. 
I have a code that uses MCE:Loop. However when I am trying to run this code in VScode debugger (using Perl Language Server) it will crash or do nothing. I get no error in the VScode Output or the Perl output or the Terminal. The VScode will either crash (without an error) or nothing will happen and the code won't even start to run. Any one else had the same issue?
Thank you

**Comment by marioroy** [comment]
Hi. You can try adding "use threads;" at the top of the script. That will cause MCE to spawn threads instead. Sadly, forking inside the debugger doesn't work.

**Comment by thalia2809** [comment]
Thanks, I tried and I m getting:
"This Perl not built to support threadsCompilation failed in require .."
I am using perl 5 v24 (v5.24.4) :/

**Comment by marioroy** [comment]
For threads to work, it requires the Perl binary to be compiled with threads support enabled.
