### ISSUE TITLE
GitHub mce-examples - 404 Page not found

### ISSUE THREAD

**Issue by KenCotterill** [marioroy/mce-perl#16]
Both [MCE](https://metacpan.org/pod/MCE) and [MCE::Examples](https://metacpan.org/dist/MCE/view/lib/MCE/Examples.pod) have the link [https://github.com/marioroy/mce-examples](https://github.com/marioroy/mce-examples).

This link produces a "404 Page not found" result. I tried before and after logging in to GitHub.

A while back, probably at least some months ago now, I definitely found the examples on GitHub. I note that [MCE v1.838](https://metacpan.org/release/MARIOROY/MCE-1.838/view/lib/MCE.pm), released on "Jan 24, 2019", has the same mce-examples URL, so that hasn't changed in almost four years.

I had a brief hunt around in [https://github.com/marioroy/mce-perl](https://github.com/marioroy/mce-perl) but couldn't find any reference to the examples page.

Please either add that page back, or update URLs in CPAN documentation to reflect a new location.

Thankyou.

**Comment by soonix** [comment]
There is a repo that looks like a copy (or "orphaned" fork) at [longbow0/mce-examples](https://github.com/longbow0/mce-examples)

**Comment by marioroy** [comment]
The [mce-examples](https://github.com/marioroy/mce-examples) repository has been restored and includes 2022 updates.
