### ISSUE TITLE
Time::Piece extremely slow under MCE::Loop on MacOS

### ISSUE THREAD

**Issue by dkechag** [marioroy/mce-perl#18]
I am having quite a bizarre issue running workloads under MCE::Loop on MacOS. Specifically, running a Time::Piece loop seems to be around *100x* slower!
This is a minimal benchmark:
```
use MCE::Loop;
use Time::Piece;

MCE::Loop::init {
    max_workers => 1,    chunk_size  => 1
};

mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    for (@{$chunk_ref}) {
        my $t = localtime() for 1..100000;
    }
} (1..1);
```

Outside MCE this takes around 0.15s on my fastest Mac, while it takes over 13s under MCE!
Note that it's not `localtime()` specifically, as the runtime is pretty much the same for this: `my $t = localtime();  $t++ for 1..10000;`.
I normally profile my code outside of MCE, so not sure how to go about this.
I have tried Perl versions from v5.20 - 5.38, an old MCE version and from intel MacOS BigSur to M2 MacOS Ventura. Always similar issue. Running a Linux docker image on those machines solves the problem, so it's MacOS specific.
For reference, my M1 Pro & M2 Ventura Macs take 13s and 18s under MCE respectively (0.15s without MCE), my old intel Big Sur takes 29s (0.4s without MCE), while if run a Debian docker image on the M1, I get 0.5s regardless of MCE or not.

Any ideas?

**Comment by marioroy** [comment]
Let's factor out MCE. On macOS, the issue persist using plain fork. Interestingly, no issues on FreeBSD.

```perl
use Time::Piece;

my $pid = fork;
die "fork failed: $!" unless defined $pid;

if (!$pid) {
    # child
    print "child  $$\n";
    my $t = localtime() for 1..100000;
    exit;
}

# parent
print "parent $$\n";
waitpid($pid, 0);
```

Let's factor out fork by adding `use threads` at the top of the script. On UNIX platforms, MCE defaults to spawning threads if the threads module is present.  No issues with Time::Piece.

```perl
use threads;
use MCE::Loop;
use Time::Piece;

MCE::Loop::init {
    max_workers => 1,
    chunk_size  => 1
};

mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    for (@{$chunk_ref}) {
        my $t = localtime() for 1..100000;
    }
} (1..1);
```

If running threads is not desired, another workaround is having each worker load the Time::Piece module individually.

```perl
use MCE::Loop;

MCE::Loop::init {
    max_workers => 1,
    chunk_size  => 1,
    user_begin  => sub {
        require Time::Piece;
        Time::Piece->import();
    }
};

mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    for (@{$chunk_ref}) {
        my $t = localtime() for 1..100000;
    }
} (1..1);
```

**Comment by marioroy** [comment]
I tried also, running `localtime()` without Time::Piece. No issues on macOS.

**Comment by marioroy** [comment]
Looking at Time::Piece, it loads two modules Time::Seconds and Time::Local. The issue appears to be Time::Local.

```perl
use Time::Local;

my $pid = fork;
die "fork failed: $!" unless defined $pid;

if (!$pid) {
    # child
    print "child  $$\n";
    my $t = localtime() for 1..100000;
    exit;
}

# parent
print "parent $$\n";
waitpid($pid, 0);
```

**Comment by marioroy** [comment]
Line [25](https://github.com/houseabsolute/Time-Local/blob/5b8d7f67b180a02ce080090d9fe1990c89d737b1/lib/Time/Local.pm#L25) in Time::Local is the root cause on macOS (slowness inside fork) for the Time::Piece module.

```perl
my $ThisYear    = ( localtime() )[5];
```

**Comment by marioroy** [comment]
This may be a Perl problem. Calling `localtime` before `fork` results in subsequent calls to `localtime` inside the child to be immensely slow on macOS.

```perl
my $t = localtime();

my $pid = fork;
die "fork failed: $!" unless defined $pid;

if (!$pid) {
    # child
    print "child  $$\n";
    my $t = localtime() for 1..100000;
    exit;
}

# parent
print "parent $$\n";
waitpid($pid, 0);
```

**Comment by dkechag** [comment]
Thanks for the nice writeup! I did doubt it would be MCE specifically (it's my preference because of how solid it's always been), but I thought it would be a good place to open an issue to verify, and it was ;)

**Comment by marioroy** [comment]
It turns out the issue is macOS-specific. I tried a Python demonstration in the other thread -- same behavior using fork.
