### ISSUE TITLE
MCE::Loop does not work for an array of ONE hash reference.

### ISSUE THREAD

**Issue by tmitanitky** [marioroy/mce-perl#23]
I'm confused with this behavior.

When using with an array of multiple hash references, it works well. 
But, something is wrong when using with an array of single hash reference. 
Is this a bug? Or is there a better way to use hash ref array with MCE?

BACKGROUND: I created a batch processing script that retrieves rows from the DB using `fetchrow_hashref` and processes each row in parallel using MCE. It had been working well, but an error occurred when only one row matched to the query occasionally (For now, my workaround is adding a meaningless hashref to the array from the beginning to keep array length longer than 1).

A code to reproduce is as follows. 
```perl
use strict;
use warnings;
use MCE::Loop;

my $value = '0';
my %hash1 = ( 'name' => 'A1', 'age' => 10);
my %hash2 = ( 'name' => 'B2', 'age' => 20);

my @refs0;
push(@refs0, \$value);

my @refs1;
push(@refs1, \%hash1);

my @refs2;
push(@refs2, \%hash1);
push(@refs2, \%hash2);

MCE::Loop->init( max_workers => 5, chunk_size=>1);
print "start mce loop for array of 1 valueref.\n";
mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    my $ref = $_;
    print "chunk_id: $chunk_id, $ref\n";
} @refs0;
print("\n");

print "start mce loop for array of 1 hashref.\n";
mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    my $ref = $_;
    print "chunk_id: $chunk_id, name: ". %{$ref}{"name"}. ", age: ". %{$ref}{"age"}. "\n";
} @refs1;
print("\n");

print "start mce loop for array of 2 hashref.\n";
mce_loop {
    my ($mce, $chunk_ref, $chunk_id) = @_;
    my $ref = $_;
    print "chunk_id: $chunk_id, name: ". %{$ref}{"name"}. ", age: ". %{$ref}{"age"}. "\n";
} @refs2;
print("\n");
```

The output is as follows:
```
start mce loop for array of 1 valueref.
chunk_id: 1, 0

start mce loop for array of 1 hashref.
Use of uninitialized value in concatenation (.) or string at /etc/hcc/test.mce.pl line 50.
chunk_id: 1, name: A1, age: 
Use of uninitialized value in concatenation (.) or string at /etc/hcc/test.mce.pl line 50.
chunk_id: 2, name: , age: 10

start mce loop for array of 2 hashref.
chunk_id: 1, name: A1, age: 10
chunk_id: 2, name: B2, age: 20
```

Both "mce loop for array of 1 valueref" and "mce loop for array of 2 hashref" are ok.
Only "start mce loop for array of 1 hashref" ouput is odd.

It seems that keys in a hash are distributed to separate chunks.
Thanks.

my env is:
perl version is v5.32.1
mce version is 1.898 installed by cpanm.

**Comment by marioroy** [comment]
When the array contains structured elements, it requires passing the array reference to mce_loop.

```perl
mce_loop { ... } \@refs0;
mce_loop { ... } \@refs1;
mce_loop { ... } \@refs2;
```

**Comment by marioroy** [comment]
> Is there a better way to use hash ref array with MCE?

Yes. Pass the array reference to mce_loop. This is helpful when the array contains array/hash refs. A one element array will work.

```perl
mce_loop { ... } \@refs0;
mce_loop { ... } \@refs1;
mce_loop { ... } \@refs2;
```

**Comment by tmitanitky** [comment]
Thank you @marioroy.

It worked perfectly for me. In my previous code, valueref array also passed  **value itself** incorrectly, and now an array reference correctly passes an **valueref**. So I also corrected `print "chunk_id: $chunk_id, $ref\n";` to  `print "chunk_id: $chunk_id, $$ref\n";`. Thank you.
