### ISSUE TITLE
How to end mce_loop_f execution early without exiting calling program.

### ISSUE THREAD

**Issue by akotlar** [marioroy/mce-perl#3]
Trying to exit mce_loop_f early, to return to a long-running perl program that calls the function that contains the mce_loop_f. I've used a synchronized, shared variable, which each worker checks at the start of the loop; however $mce->shutdown() from within a worker results in re-spawning of workers, the loop doesn't end until the rest of the file is read

Another approach was to handle cleanup in the parent process, and then die/croak or use MCE::Signal->stop_and_exit("TERM")  (or "INT"). In the former solution, control returns back to the caller, but subsequent calls to the function bearing mce_loop_f results in "MCE::shutdown: method is not allowed...". 

Using MCE::Signal->stop_and_exit exist the entire program, including the caller. I just want to break early from the function that calls mce_loop_f, not exit the program. Have tried to use SIG{TERM} to "catch", but this doesn't prevent the program from exiting, just allows me to run a function before exiting. Similarly, wrapping in Try::Catch doesn't prevent exit. I am clearly new to the use of sigtrap or SIG{...} handlers.

Wondering if sigtrap is the recommended way. It would be nice if there were just a way to use MCE::Signal->stop_and_exit , or MCE::Loop::finish to end mce_loop_f, and continue execution to the code below it.

Thank you.

**Comment by marioroy** [comment]
Hello, have you tried MCE->abort()? That will have workers exit early without exiting the entire program.

**Comment by akotlar** [comment]
Hi @marioroy , thanks very much for your reply. Yes, I have, and that works as expected; maybe this is my confusion, but I did not understand why MCE::Loop::finish would not have the same effect, or why $mce->shutdown within the loop would lead to workers to continue to the next iteration as if no shutdown was issued.

$mce->abort() works, but leads to the following behavior: When using a pipe to read the file (in testing, a compressed file, via gzip or pigz), $mce->abort() causes all workers & gzip/pigz go to sleep, and it becomes impossible to return from the function, or close the file handle.

Do you know why?

**Comment by marioroy** [comment]
MCE::Loop::finish and $mce->shutdown are for the main process, not to be called by workers. This is unless workers instantiate MCE themselves (nested sessions). I will take a look at piping data and aborting early.

**Comment by akotlar** [comment]
Thanks. I was using MCE::Loop:finish in the main process, that shutdown error would occur on the following execution of the function that calls MCE. Something is being stored statically that prevents the re-initializaiton of MCE::Loop it seems.

It sounds like I was using $mce->shutdown inappropriately, so the workers not terminating is not a part of this issue.

Thanks for looking into the piping data issue.

**Comment by marioroy** [comment]
I like to reproduce the issue with MCE::Loop::finish, but am unable to. Can you provide a small test case and the MCE version being used. That will be very helpful. I understand the piping data / abort early issue and can validate that. What OS are you running on?

**Comment by akotlar** [comment]
In further testing, it looks like after MCE->abort() is called; further calls to the function that initializes MCE::Loop will fail to actually make workers

In this (incomplete) toy example, after ctrl + c, control is return to the package (let's call it Parent), that works fine; but in the next iteration of Parent's loop, nothing will happen within the mce_loop_f. top shows no process spawned.

``` perl
package Parent;

while(1) {
  my $obj = Example->new();
 $obj->run();
}

package Example;

use Moose; #or Mouse;

sub BUILD {
 # initialize class object
}

sub run {
 local $SIG{INT} = sub {
    my $message = shift;

    $aborted = 1;

    MCE->abort();
  };

open(my $fh, '<', '/path/to/file');

  mce_loop_f {
    # process something large
  } $fh;

  if($aborted) {
    ## clean up

   return;
  }
}
```

edit: system is linux AMI (i2.2xlarge ec2 instance), based on centos I believe.

**Comment by marioroy** [comment]
Thank you for the clarification and small test case. That is very valuable. Fortunately, all is fine with MCE 1.608, 1.708, and 1.804 on CentOS 7.2.1511. Ctrl-C works as expected and begins all over again.

I use your test case with slight modification.

``` perl
package Example;

use Moose; # or Mouse;
use MCE::Loop;

sub BUILD {
  # initialize class object
}

sub run {
  my $aborted = 0;   # important, reset back to 0

  local $SIG{INT} = sub {
    my $message = shift;
    $aborted = 1;
    MCE->abort();
  };

  open(my $fh, '<', 'big.txt');

  mce_loop_f {
    # process something large
    print MCE->chunk_id(), "\n";
  } $fh;

  if($aborted) {
    ## clean up
    return;
  }
}

1;

package Main;

$| = 1;

while(1) {
  my $obj = Example->new();
  print "Thank you for this test case :)\n";
  $obj->run();
}
```

**Comment by marioroy** [comment]
The same is working via a pipe. I added a sleep to slow the process down.

``` perl
package Example;

use Time::HiRes 'sleep';
use Moose; # or Mouse;
use MCE::Loop;

sub BUILD {
  # initialize class object
}

sub run {
  my $aborted = 0;   # important, reset back to 0

  local $SIG{INT} = sub {
    my $message = shift;
    $aborted = 1;
    MCE->abort();
  };

# open(my $fh, '<', 'big.txt');
  open(my $fh, 'cat big.txt |');

  mce_loop_f {
    # process something large
    print MCE->chunk_id(), "\n";
    sleep 0.01;
  } $fh;

  if($aborted) {
    ## clean up
    return;
  }
}

1;

package Main;

$| = 1;

while(1) {
  my $obj = Example->new();
  print "Thank you for this test case :)\n";
  $obj->run();
}
```

**Comment by akotlar** [comment]
Thank you. This is very helpful. Given your tests it is clearly something in the rest of my application, although I'm not sure what could cause the behavior that I'm seeing. I think we can consider this issue closed :)

**Comment by marioroy** [comment]
Got it. Thanks.
