### ISSUE TITLE
It does not block with the dequeue after dequeue_nb.

### ISSUE THREAD

**Issue by bokutin** [marioroy/mce-perl#8]
Hi.

％ cat dequeue_nb.pl 

    #!/usr/bin/env perl
    use MCE;
    use MCE::Queue;
    my $q = MCE::Queue->new;
    $q->enqueue(1);
    print $q->dequeue_nb;
    print $q->dequeue; ＃ blocking?
    die "I did not block with the above code. Is this correct?";

％ perl dequeue_nb.pl
I did not block with the above code. Is this correct? at dequeue_nb.pl line 8.
1％

**Comment by marioroy** [comment]
Hi Tomohiro,

This is fixed for the 1.830 release and committed into trunk. MCE 1.830 will be released on CPAN in a couple of days.

Thank you for the bug report.

Regards, Mario

**Comment by bokutin** [comment]
Thank you for the quick fix!

A similar problem seems to occur also in MCE::Shared.

％ cat ./dequeue_nb.pl

    #!/usr/bin/env perl
    use lib "mce-perl/lib";
    use MCE;
    use MCE::Shared;
    my $q = MCE::Shared->queue;
    $q->enqueue(1);
    print $q->dequeue_nb;
    print $q->dequeue;
    die "I did not block with the above code. Is this correct?";

％ perl ./dequeue_nb.pl
I did not block with the above code. Is this correct? at ./dequeue_nb.pl line 10, <__ANONIO__> line 2.
1％

**Comment by marioroy** [comment]
Hi Tomohiro,

To not miss this, I fixed MCE::Shared locally on my machine and want to complete the change log and documentation before committing into Github. MCE::Shared 1.827 will be released in a couple of days along with MCE 1.830.

Thank you.

Regards, Mario

**Comment by bokutin** [comment]
Sorry to bother you, but thank you very much for your time.

**Comment by marioroy** [comment]
Hi Tomohiro,

All the updates completed thus far for MCE::Shared were committed into Github. Upon doing the documentation updates, I realized there is more to do. I will try to finish by the end of August.

Thank you again for this bug report. Both MCE::Queue and MCE::Shared::Queue are current.

Regards, Mario

**Comment by marioroy** [comment]
MCE 1.830 was released today containing the fix. Thank you.
